### ISSUE TITLE
Cannot find module 'js-yaml'

### ISSUE THREAD

**Issue by rndmax** [mozilla/high-fidelity#95]
hi. please help newbie

```
$ bower install
module.js:339
    throw err;
    ^

Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/configstore/index.js:9:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

**Comment by tofumatt** [comment]
Sorry but this project is basically abandoned at this point. I'll update the README, but I don't think think project still works.
